### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by chausner-audeering** [audeering/sphinx-audeering-theme#23]
In all internal and external packages that I tested that use our theme, the search never produces any results. There is a JavaScript error that's probably causing this:

> Uncaught ReferenceError: Search is not defined
    <anonymous> ..../docs/build/html/search.html?q=vad&check_keywords=yes&area=default:243

It's happening at this location inside search.html:
```html
<script type="text/javascript">
    jQuery(function() { Search.loadIndex("searchindex.js"); });
</script>
```

I tried the fix/workaround mentioned [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931541#10), inserting
```html
<script type="text/javascript" src="_static/searchtools.js"></script>
```
into search.html, and it works.

[Here](https://github.com/readthedocs/sphinx_rtd_theme/blob/e2b60d7e7b2b6feb8a45b224950608ad11668a7e/sphinx_rtd_theme/search.html#L15) the `searchtools.js` should normally be included in sphinx-rtd-theme. Note that it is within a `{%- block scripts %}`. Is that block maybe somehow getting overridden? Somebody else had the same issue but no solution was posted: https://github.com/readthedocs/sphinx_rtd_theme/issues/832

**Comment by hagenw** [comment]
That's interesting. I can confirm the bug, when I build the documentation locally. The funny thing is we don't overwrite `search.html`, so I'm not sure yet why `_static/searchtools.js` is missing.

I will try to find a workaround.
