### ISSUE TITLE
New theme has very bright red

### ISSUE THREAD

**Issue by chausner-audeering** [audeering/sphinx-audeering-theme#42]
I understand that we adapted the colors to the brighter colors of our new homepage. Nevertheless, I find the new red color tone in the upper left behind the logo to be very bright and somewhat distracting from the content. Maybe there are alternative color tones from the new homepage that are easier on the eyes, that we could use? Some tone between the previous darker red and the new light red maybe.

The new bright red seems fine for links and text but the big solid area in the top-left makes it really stand out.

**Comment by hagenw** [comment]
One possibility would be to apply a gradient as we do in the icon:

![image](https://user-images.githubusercontent.com/173624/142259723-29de1c4b-0531-47d5-b022-1660cf18d2bf.png)

but I'm not sure if this really looks better.
Need to first get the exact gradient settings in order to test it.

**Comment by chausner-audeering** [comment]
I think I have gotten used to the newer color, at least I do not find it that distracting anymore. :) I still think it's very bright but probably still in an acceptable range.

**Comment by hagenw** [comment]
OK, we will stay with the current red color.
