### ISSUE TITLE
Unify inline code presentation?

### ISSUE THREAD

**Issue by hagenw** [audeering/sphinx-audeering-theme#46]
At the moment inline code outside of the API is presented not in bold as I think it makes reading more pleasant in text.
But it could mean that we have some mix if we also use a link to another class, e.g.

![image](https://user-images.githubusercontent.com/173624/143408355-a356dabc-86fe-4edd-9f97-b144eee942eb.png)

We could change to use bold font for all inline code instead:

![image](https://user-images.githubusercontent.com/173624/143408907-0c7471e9-b2dd-4541-bf65-1d2115eae223.png)

In addition, @chausner-audeering proposed to also use the same font color:

![image](https://user-images.githubusercontent.com/173624/143409074-2a7258bf-934d-402e-bd76-9b4e0c65961a.png)

In the API it would then change from

![image](https://user-images.githubusercontent.com/173624/143409262-7e2bd1c5-77dd-4c31-8d45-14e649f92641.png)

to

![image](https://user-images.githubusercontent.com/173624/143409336-67f85716-0bfe-4bd4-8132-b9b15c95aa20.png)

**Comment by hagenw** [comment]
@frankenjoe, @drux007 any opinions on this issue?

**Comment by frankenjoe** [comment]
I like that the function name is now better separated from its argument.

**Comment by hagenw** [comment]
You are referring to 

![image](https://user-images.githubusercontent.com/173624/146017761-37ae7f0d-86e9-4cdd-b4d9-e841f240e964.png)

vs.

![image](https://user-images.githubusercontent.com/173624/146017718-f990dbf8-3f9e-450f-ac30-93bafded4cfc.png)

Unfortunately, this is not really the topic of this issue.
I also like the approach with having the function name written in black better, but I have not yet identified if it is the version of sphinx or the RTD theme that makes it appear black or not. I crated https://github.com/audeering/sphinx-audeering-theme/issues/49 to track this.

Here, we are talking mainly about these two questions:

* use bold for inline code at all occurrences
* change the color of inline code to the same as the normal text

**Comment by frankenjoe** [comment]
Sorry, I thought it would also change since this was the most obvious change between the two images :) Regaridng bold and normal text, I don't have a strong opinion.

**Comment by drux007** [comment]
Would it also result in losing **bullet points** in API @hagenw ?

You posted from:
![143409262-7e2bd1c5-77dd-4c31-8d45-14e649f92641](https://user-images.githubusercontent.com/17862991/146026086-e7bbbf16-d6e7-44be-a1dd-8f8512324f50.png)
to:
![143409336-67f85716-0bfe-4bd4-8132-b9b15c95aa20](https://user-images.githubusercontent.com/17862991/146026094-cfc141d6-b0d3-40df-b8bc-2608f44f5806.png)
I would keep them, if possible.

If that's only a typo, I would say the difference between using bold and changing the color to the same as the normal text is really minor according to the images you posted, but if I really have to pick one, I would go with **same font color**.

**Comment by hagenw** [comment]
Sorry, it seems I used different versions of the theme when generating those example figures.
The bullet points are no longer part of the theme and not part of the discussion for this issue, compare 
https://audeering.github.io/audb/api.html#load

As there are no strong objections against the proposed changes, I think I will simply apply them. Using bold font everywhere avoids that users start thinking about what might be the meaning behind it when there is no meaning. Also the devAIce team is using the changes here anyway as they customized the theme.
